-- Run this in Supabase SQL Editor.
create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  title text not null,
  image_url text not null,
  sort_order bigint not null default 0,
  created_at timestamptz not null default now()
);

alter table public.gallery enable row level security;

create policy "Public can view gallery"
on public.gallery for select
to anon, authenticated
using (true);

create policy "Authenticated admin can insert gallery"
on public.gallery for insert
to authenticated
with check (true);

create policy "Authenticated admin can update gallery"
on public.gallery for update
to authenticated
using (true)
with check (true);

create policy "Authenticated admin can delete gallery"
on public.gallery for delete
to authenticated
using (true);

-- IMPORTANT:
-- Create the one admin account in Supabase Authentication.
-- Do not put the admin password in HTML/JavaScript.
